name: Hello World Workflow

# 触发条件：当代码推送到主分支时触发
on:
  push:
    branches:
      - main # 如果你的默认分支是master，请将其改为master

jobs:
  say-hello:
    runs-on: ubuntu-latest # 使用最新版的Ubuntu运行环境

    steps:
    - name: Print Hello World
      run: echo "Hello World!"
